clean :
	@rm -f stochastic_pipe.dag \
	stochastic_pipe.dag.condor.sub \
	stochastic_pipe.dag.dagman.log \
	stochastic_pipe.dag.dagman.out \
	stochastic_pipe.dag.lib.out \
	stochastic_pipe.dag.rescue \
	stochastic_pipe.log \
	err.* \
	out.*; \
	rm -f input/cachefiles/*.txt output/*.*

