all:

clean:
	rm -f example_*.dat example.job*.mat example_combined.job*.mat; \
	rm -f H1L1*.dat H1L1*.png H1L1*.eps H1L1*.fig *_resumeCRfMJ.mat badGPSTimes.dat example_datestamp.txt; \
	rm -f radiometer_ccspectra.job3.trial1.dat radiometer_combined_ccspectra.job3.trial1.dat \
		radiometer_combined_ccstats.job3.trial1.dat radiometer_combined_sensints.job3.trial1.dat \
		radiometer_naivesigmas.job3.trial1.dat radiometer_optimal.job3.trial1.dat \
		radiometer_orf.job3.trial1.dat radiometer_params.job3.dat \
		radiometer_psd1.job3.trial1.dat radiometer_psd2.job3.trial1.dat \
		radiometer_sensints.job3.trial1.dat \
		radiometer_ccstatsSky.job3.trial1.mat radiometer_ccstatsSkySet1.job3.trial1.mat; \
	rm -rf old/output/*; \
	rm -rf cachefiles_server
